version: 0.2
env:
  variables:
    APP_NAME: "codebuild-demo"
    # SSM Parameter Store Values
    # parameter-store:
    # sercret from aws secret manager
  secrets-manager:
    DOCKER_USERNAME: arn:aws:secretsmanager:ap-southeast-1:340752821097:secret:nicely/codebuild-demo-9SPwfN:username
    DOCKER_PASSWORD: arn:aws:secretsmanager:ap-southeast-1:340752821097:secret:nicely/codebuild-demo-9SPwfN:token
    ECR_URL: arn:aws:secretsmanager:ap-southeast-1:340752821097:secret:nicely/codebuild-demo-9SPwfN:ecr-url
  
phases:
  install:
    commands:
      - echo "Install Phase - Nothing to do using latest Amazon Linux Docker Image for CodeBuild which has all AWS Tools - https://github.com/aws/aws-codebuild-docker-images/blob/master/al2/x86_64/standard/3.0/Dockerfile"
  pre_build:
      commands:
        - echo "Building the Docker image..."
        - echo $DOCKER_USERNAME
        - echo $DOCKER_PASSWORD
        - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        - TAG="$(git describe --tags --abbrev=0)"
        - echo "Show env variables"
        - env
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build --tag $APP_NAME:$TAG .
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR Repository"   
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin $ECR_URL     
      - docker tag $APP_NAME:$TAG $ECR_URL/$APP_NAME:$TAG 
      - docker push $ECR_URL/$APP_NAME:$TAG 
# artifacts:
#   files: 
#     - build.json   
#     - kube-manifests/*